#!/bin/sh

. /etc/control.d/functions-local-policy

CONFIG=/etc/samba/smb.conf

new_subst disabled '^#[[:space:]]*usershare[[:space:]]+path' 's,^[[:space:]]*usershare[[:space:]]\+path,#\tusershare path,#\1,'
new_subst enabled '^[[:space:]]*usershare[[:space:]]+path' 's,^#[[:space:]]*usershare[[:space:]]\+path,\tusershare path,#\1,'

new_help disabled 'Disable smb usershare options'
new_help enabled 'Enable smb usershare options'

new_summary 'Control for work usershare options'

if is_file_exists "$CONFIG" && ! is_builtin_mode "$1"; then
	case "$1" in
	disabled|enabled)
		if ! grep -q '^\s*#\?\s*usershare\s\+path\s*=\s*' "$CONFIG"; then
			sed -i --follow-symlinks -e '/\[global\]/a \\tusershare path = /var/lib/samba/usershares' $CONFIG
			if ! grep -q '^\s*#\?\s*usershare\s\+max\s\+shares\s*=\s*' "$CONFIG"; then
				sed -i --follow-symlinks -e '/\[global\]/a \\tusershare max shares = 100' $CONFIG
			fi
			if ! grep -q '^\s*#\?\s*usershare\s\+allow\s\+guests\s*=\s*' "$CONFIG"; then
				sed -i --follow-symlinks -e '/\[global\]/a \\tusershare allow guests = yes' $CONFIG
			fi
			if ! grep -q '^\s*#\?\s*usershare\s\+owner\s\+only\s*=\s*' "$CONFIG"; then
				sed -i --follow-symlinks -e '/\[global\]/a \\tusershare owner only = yes' $CONFIG
			fi
		fi
		;;
	esac
fi

control_subst_with_file_check "$CONFIG" "$*" "disabled enabled"
